image: Ubuntu

install:
- sh: >-
    npm install pm2 -g pm2 update

    ls

    pm2 bin/www

test_script:
- npm test

build:
  publish_wap: true
  verbosity: minimal
pull_requests:
  do_not_increment_build_number: true

artifacts:
- path: artifacts
  name: wechat-express-azure

before_deploy:
- sh: npm install pm2

deploy:
  - provider: AzureWebJob
    website: wechat-express-azure-website
    username: root
    password: Newpark0521
    artifact: wechat-express-azure-website.zip
    job_name: wechat-express-azure-website-job
    job_schedule: '* 0 * * * *'