image: Ubuntu

install:
- sh: >-
    npm install pm2 -g pm2 update

    ls

  # pm2 start bin/www

test_script:
- npm test

build:
    script:
        - npm install
    artifacts:
        name: wechat-express-azure-website.zip
        expire_in: 10 mins
        paths:
            - node_modules

artifacts:
- path: wechat-express-azure-website.zip
  name: wechat-express-azure

before_deploy:
- sh: >-
    ifconfig

    pm2 start bin/www

deploy:
  - provider: AzureWebJob
    website: wechat-express-azure-website
    username: root
    password: Newpark0521
    artifact: wechat-express-azure-website.zip
    job_name: wechat-express-azure-website-job
    job_schedule: '* 0 * * * *'